/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { DatabaseService } from "../database.service";
import { DatabaseCreateInput } from "./DatabaseCreateInput";
import { DatabaseWhereInput } from "./DatabaseWhereInput";
import { DatabaseWhereUniqueInput } from "./DatabaseWhereUniqueInput";
import { DatabaseFindManyArgs } from "./DatabaseFindManyArgs";
import { DatabaseUpdateInput } from "./DatabaseUpdateInput";
import { Database } from "./Database";

export class DatabaseGrpcControllerBase {
  constructor(protected readonly service: DatabaseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Database })
  @GrpcMethod("DatabaseService", "createDatabase")
  async createDatabase(
    @common.Body() data: DatabaseCreateInput
  ): Promise<Database> {
    return await this.service.createDatabase({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Database] })
  @ApiNestedQuery(DatabaseFindManyArgs)
  @GrpcMethod("DatabaseService", "databases")
  async databases(@common.Req() request: Request): Promise<Database[]> {
    const args = plainToClass(DatabaseFindManyArgs, request.query);
    return this.service.databases({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DatabaseService", "database")
  async database(
    @common.Param() params: DatabaseWhereUniqueInput
  ): Promise<Database | null> {
    const result = await this.service.database({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DatabaseService", "updateDatabase")
  async updateDatabase(
    @common.Param() params: DatabaseWhereUniqueInput,
    @common.Body() data: DatabaseUpdateInput
  ): Promise<Database | null> {
    try {
      return await this.service.updateDatabase({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DatabaseService", "deleteDatabase")
  async deleteDatabase(
    @common.Param() params: DatabaseWhereUniqueInput
  ): Promise<Database | null> {
    try {
      return await this.service.deleteDatabase({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
