/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Query } from "./Query";
import { QueryCountArgs } from "./QueryCountArgs";
import { QueryFindManyArgs } from "./QueryFindManyArgs";
import { QueryFindUniqueArgs } from "./QueryFindUniqueArgs";
import { DeleteQueryArgs } from "./DeleteQueryArgs";
import { QueryService } from "../query.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Query)
export class QueryResolverBase {
  constructor(
    protected readonly service: QueryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "any",
  })
  async _queriesMeta(
    @graphql.Args() args: QueryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Query])
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "any",
  })
  async queries(@graphql.Args() args: QueryFindManyArgs): Promise<Query[]> {
    return this.service.queries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Query, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "read",
    possession: "own",
  })
  async query(
    @graphql.Args() args: QueryFindUniqueArgs
  ): Promise<Query | null> {
    const result = await this.service.query(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Query)
  @nestAccessControl.UseRoles({
    resource: "Query",
    action: "delete",
    possession: "any",
  })
  async deleteQuery(
    @graphql.Args() args: DeleteQueryArgs
  ): Promise<Query | null> {
    try {
      return await this.service.deleteQuery(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
